class_name Tag_List extends Node

const PHYSICAL = "PHYSICAL"
const ELEMENTAL = "ELEMENTAL"
const LIGHTNING = "LIGHTNING"
const FIRE = "FIRE"
const COLD = "COLD"
const DEFENSE = "DEFENSE"
const ATTACK = "ATTACK"
const MAGIC = "MAGIC"
const DOT = "DOT"
const SPEED = "SPEED"
const FLAT = "FLAT"
const PERCENTAGE = "PERCENTAGE"
const CRITICAL = "CRITICAL"
const WEAPON = "WEAPON"
const ARMOR = "ARMOR"
const ENERGY_SHIELD = "ENERGY_SHIELD"
const MANA = "MANA"
const MOVEMENT = "MOVEMENT"

enum StatType {
	FLAT_DAMAGE,
	INCREASED_DAMAGE,
	INCREASED_SPEED,
	CRIT_CHANCE,
	CRIT_DAMAGE,
	FLAT_ARMOR,
	FLAT_ENERGY_SHIELD,
	FLAT_HEALTH,
	FLAT_MANA,
	MOVEMENT_SPEED,
}
