class_name Tag_List extends Node

const PHYSICAL = "PHYSICAL"
const ELEMENTAL = "ELEMENTAL"
const LIGHTNING = "LIGHTNING"
const FIRE = "FIRE"
const COLD = "COLD"
const DEFENSE = "DEFENSE"
const ATTACK = "ATTACK"
const MAGIC = "MAGIC"
const DOT = "DOT"
const SPEED = "SPEED"
const FLAT = "FLAT"
const PERCENTAGE = "PERCENTAGE"
const CRITICAL = "CRITICAL"
const WEAPON = "WEAPON"
const ARMOR = "ARMOR"
const ENERGY_SHIELD = "ENERGY_SHIELD"
const MANA = "MANA"
const MOVEMENT = "MOVEMENT"
const UTILITY = "UTILITY"
const EVASION = "EVASION"
# Element types
const CHAOS = "CHAOS"
# Damage channels
const SPELL = "SPELL"
# Archetype identity
const STR = "STR"
const DEX = "DEX"
const INT = "INT"

enum StatType {
	FLAT_DAMAGE,
	INCREASED_DAMAGE,
	INCREASED_SPEED,
	CRIT_CHANCE,
	CRIT_DAMAGE,
	FLAT_ARMOR,
	FLAT_ENERGY_SHIELD,
	FLAT_HEALTH,
	FLAT_MANA,
	MOVEMENT_SPEED,
	PERCENT_ARMOR,
	PERCENT_EVASION,
	PERCENT_ENERGY_SHIELD,
	PERCENT_HEALTH,
	FLAT_EVASION,
	FIRE_RESISTANCE,
	COLD_RESISTANCE,
	LIGHTNING_RESISTANCE,
	ALL_RESISTANCE,
	# Spell damage stats
	FLAT_SPELL_DAMAGE,
	INCREASED_SPELL_DAMAGE,
	INCREASED_CAST_SPEED,
	FLAT_SPELL_LIGHTNING_DAMAGE,
	FLAT_SPELL_FIRE_DAMAGE,
	# DoT damage stats
	BLEED_DAMAGE,
	POISON_DAMAGE,
	BURN_DAMAGE,
	# Chaos resistance
	CHAOS_RESISTANCE,
	# DoT chance stats
	BLEED_CHANCE,
	POISON_CHANCE,
	BURN_CHANCE,
}
